const products = {
    gaming: [
        { id: 'g1', name: 'Gaming Laptop', price: 1200, category: 'gaming' },
        { id: 'g2', name: 'Mechanical Keyboard', price: 150, category: 'gaming' },
        { id: 'g3', name: 'Gaming Monitor', price: 300, category: 'gaming' },
        { id: 'g4', name: 'Gaming Mouse', price: 80, category: 'gaming' },
        { id: 'g5', name: 'VR Headset', price: 400, category: 'gaming' },
        { id: 'g6', name: 'Gaming Chair', price: 250, category: 'gaming' },
        { id: 'g7', name: 'Streaming Microphone', price: 100, category: 'gaming' },
        { id: 'g8', name: 'RGB Lighting Kit', price: 50, category: 'gaming' },
        { id: 'g9', name: 'External SSD (1TB)', price: 150, category: 'gaming' },
        { id: 'g10', name: 'Capture Card', price: 200, category: 'gaming' },
    ],
    electronics: [
        { id: 'e1', name: '4K Smart TV', price: 800, category: 'electronics' },
        { id: 'e2', name: 'Wireless Earbuds', price: 120, category: 'electronics' },
        { id: 'e3', name: 'Smartphone', price: 900, category: 'electronics' },
        { id: 'e4', name: 'Smartwatch', price: 250, category: 'electronics' },
        { id: 'e5', name: 'Bluetooth Speaker', price: 100, category: 'electronics' },
        { id: 'e6', name: 'Portable Power Bank', price: 50, category: 'electronics' },
        { id: 'e7', name: 'Noise-Canceling Headphones', price: 300, category: 'electronics' },
        { id: 'e8', name: 'Drone with Camera', price: 500, category: 'electronics' },
        { id: 'e9', name: 'Smart Home Hub', price: 200, category: 'electronics' },
        { id: 'e10', name: 'E-Reader', price: 130, category: 'electronics' },
    ],
    furniture: [
        { id: 'f1', name: 'Modern Sofa', price: 1500, category: 'furniture' },
        { id: 'f2', name: 'Office Chair', price: 300, category: 'furniture' },
        { id: 'f3', name: 'Dining Table', price: 700, category: 'furniture' },
        { id: 'f4', name: 'Bookshelf', price: 200, category: 'furniture' },
        { id: 'f5', name: 'Coffee Table', price: 150, category: 'furniture' },
        { id: 'f6', name: 'Wardrobe', price: 600, category: 'furniture' },
        { id: 'f7', name: 'Recliner', price: 500, category: 'furniture' },
        { id: 'f8', name: 'Bar Stool', price: 120, category: 'furniture' },
        { id: 'f9', name: 'Vanity Table', price: 350, category: 'furniture' },
        { id: 'f10', name: 'Outdoor Bench', price: 400, category: 'furniture' },
    ],
    fitness: [
        { id: 'ft1', name: 'Treadmill', price: 1000, category: 'fitness' },
        { id: 'ft2', name: 'Dumbbells Set', price: 200, category: 'fitness' },
        { id: 'ft3', name: 'Yoga Mat', price: 50, category: 'fitness' },
        { id: 'ft4', name: 'Exercise Bike', price: 700, category: 'fitness' },
        { id: 'ft5', name: 'Resistance Bands', price: 40, category: 'fitness' },
        { id: 'ft6', name: 'Pull-up Bar', price: 100, category: 'fitness' },
        { id: 'ft7', name: 'Kettlebell', price: 80, category: 'fitness' },
        { id: 'ft8', name: 'Rowing Machine', price: 900, category: 'fitness' },
        { id: 'ft9', name: 'Foam Roller', price: 30, category: 'fitness' },
        { id: 'ft10', name: 'Fitness Tracker', price: 200, category: 'fitness' },
    ]
};
